name: lamp
description: "LAMP - Limitless Advancement Mentoring Program"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Routing
  go_router: ^15.1.2
  
  # Internationalization
  intl: ^0.20.2
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Backend
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
